name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]

permissions: write-all

jobs:
  dependabot:
    # If its check_suite completed successfully,
    # AND it's from a pull request,
    # AND the pull request is from dependabot[bot],
    # AND the pull request is assigned to cnuss,
    # then post a PR comment that says "@claude Please merge this PR"
    if: |
      github.event_name == 'check_suite' && 
      github.event.check_suite.conclusion == 'success' &&
      github.event.check_suite.pull_requests &&
      github.event.check_suite.pull_requests[0] &&
      github.actor == 'dependabot[bot]' &&
      github.event.check_suite.pull_requests[0].state == 'open' &&
      contains(github.event.check_suite.pull_requests[0].assignees.*.login, 'cnuss')
    runs-on: ubuntu-latest
    steps:
      - name: Request Claude merge
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.check_suite.pull_requests[0].number;

            console.log(`Requesting Claude to merge PR #${pull_number}`);

            // Post comment to trigger Claude merge
            const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues/${pull_number}/comments`, {
              method: 'POST',
              headers: {
                'Authorization': 'Bearer ${{ secrets.COMMENT_BOT_TOKEN }}',
                'Accept': 'application/vnd.github.v3+json',
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                body: '@claude Please merge this PR'
              })
            });

            if (!response.ok) {
              throw new Error(`Failed to create comment: ${response.status} ${response.statusText}`);
            }

            console.log(`Successfully requested Claude to merge PR #${pull_number}`);
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: saml-to/assume-aws-role-action@v1
        with:
          role: arn:aws:iam::557208059266:role/aws@scaffold.ly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          use_bedrock: true
        env:
          AWS_REGION: us-east-1
